site_name: Larry's Folk
docs_dir: Larry's Folk
repo_url: https://github.com/conumey/icewind-tales
theme:
  name: material
  features:
    - toc.follow
    - navigation.top
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: deep purple
      accent: yellow
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - ezlinks
  - awesome-pages:
        collapse_single_pages: true
  - pagenav-generator
  - tags