name: test-build-docs

on:
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-ezlinks-plugin
      - run: pip install mkdocs-ezlinked-plugin
      - run: mkdocs build
